"""Add RS fields and RSCalculationTask model

Revision ID: 1cc07932927c
Revises: 9fa4e8dfb6f3
Create Date: 2025-11-08 14:50:44.698908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc07932927c'
down_revision = '9fa4e8dfb6f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rs_vs_subsector', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rs_vs_sector', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rs_base_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rs_updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_instruments_rs_vs_sector'), ['rs_vs_sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_rs_vs_subsector'), ['rs_vs_subsector'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_rs_vs_subsector'))
        batch_op.drop_index(batch_op.f('ix_instruments_rs_vs_sector'))
        batch_op.drop_column('rs_updated_at')
        batch_op.drop_column('rs_base_date')
        batch_op.drop_column('rs_vs_sector')
        batch_op.drop_column('rs_vs_subsector')

    # ### end Alembic commands ###
