"""Add Kite Connect integration models

Revision ID: 27ba45b34787
Revises: 
Create Date: 2025-11-03 19:46:29.580012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ba45b34787'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kite_access_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('kite_access_token_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('kite_user_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('kite_public_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('kite_refresh_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('kite_connected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('kite_last_connected', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('kite_last_connected')
        batch_op.drop_column('kite_connected')
        batch_op.drop_column('kite_refresh_token')
        batch_op.drop_column('kite_public_token')
        batch_op.drop_column('kite_user_id')
        batch_op.drop_column('kite_access_token_expires')
        batch_op.drop_column('kite_access_token')

    # ### end Alembic commands ###
