"""Add index_symbol to sectors and subsectors, create index_history table

Revision ID: 3ffc33d1f6bb
Revises: 7c67dc958c4e
Create Date: 2025-11-05 22:40:34.229848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ffc33d1f6bb'
down_revision = '7c67dc958c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index_symbol', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_sectors_index_symbol'), ['index_symbol'], unique=True)

    with op.batch_alter_table('sub_sectors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index_symbol', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_sub_sectors_index_symbol'), ['index_symbol'], unique=True)

    # Create index_history table
    op.create_table(
        'index_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('index_symbol', sa.String(length=10), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('index_value', sa.Float(), nullable=False),
        sa.Column('index_calculated_date', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('index_symbol', 'date', name='uq_index_symbol_date')
    )
    op.create_index(op.f('ix_index_history_index_symbol'), 'index_history', ['index_symbol'], unique=False)
    op.create_index(op.f('ix_index_history_date'), 'index_history', ['date'], unique=False)
    op.create_index('idx_index_history_lookup', 'index_history', ['index_symbol', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop index_history table
    op.drop_index('idx_index_history_lookup', table_name='index_history')
    op.drop_index(op.f('ix_index_history_date'), table_name='index_history')
    op.drop_index(op.f('ix_index_history_index_symbol'), table_name='index_history')
    op.drop_table('index_history')

    with op.batch_alter_table('sub_sectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_sectors_index_symbol'))
        batch_op.drop_column('index_symbol')

    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sectors_index_symbol'))
        batch_op.drop_column('index_symbol')

    # ### end Alembic commands ###
