"""Add historical data settings table

Revision ID: 7cd284eab3f2
Revises: d3cc5a8e5507
Create Date: 2025-11-04 19:31:08.910195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd284eab3f2'
down_revision = 'd3cc5a8e5507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_tradingsymbol'))
        batch_op.create_index(batch_op.f('ix_instruments_tradingsymbol'), ['tradingsymbol'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_tradingsymbol'))
        batch_op.create_index(batch_op.f('ix_instruments_tradingsymbol'), ['tradingsymbol'], unique=False)

    # ### end Alembic commands ###
