"""Add stock stage analysis fields and task model

Revision ID: 9fa4e8dfb6f3
Revises: 24f7f4641667
Create Date: 2025-11-08 00:55:07.630775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa4e8dfb6f3'
down_revision = '24f7f4641667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Note: stock_stage_analysis_tasks table already exists (auto-created by SQLAlchemy)
    # Only need to add columns to instruments table

    # Add stage analysis columns to instruments table
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_stage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stage_updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('stage_confidence', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_instruments_current_stage'), ['current_stage'], unique=False)

    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sectors_current_stage'), ['current_stage'], unique=False)

    with op.batch_alter_table('sub_sectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_sectors_current_stage'), ['current_stage'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_sectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_sectors_current_stage'))

    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sectors_current_stage'))

    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_current_stage'))
        batch_op.drop_column('stage_confidence')
        batch_op.drop_column('stage_updated_at')
        batch_op.drop_column('current_stage')

    # Note: Not dropping stock_stage_analysis_tasks table as it was auto-created
    # and might be needed by other parts of the application

    # ### end Alembic commands ###
