"""Add ScanResultStock model and progress_message to ScannerTask

Revision ID: c0822eab356e
Revises: b7c8d9e0f1a2
Create Date: 2025-11-11 22:28:21.152244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0822eab356e'
down_revision = 'b7c8d9e0f1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanner_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanner_tasks', schema=None) as batch_op:
        batch_op.drop_column('progress_message')

    # ### end Alembic commands ###
