"""Add master_sync_tasks table for orchestrating multi-step data synchronization

Revision ID: d1e2f3a4b5c6
Revises: c0822eab356e
Create Date: 2025-11-12 15:55:00.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'd1e2f3a4b5c6'
down_revision = 'c0822eab356e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_sync_tasks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('progress_percentage', sa.Float(), nullable=True),
        sa.Column('current_step', sa.Integer(), nullable=True),
        sa.Column('current_step_name', sa.String(length=100), nullable=True),
        sa.Column('total_steps', sa.Integer(), nullable=True),
        sa.Column('download_task_id', sa.Integer(), nullable=True),
        sa.Column('sync_task_id', sa.Integer(), nullable=True),
        sa.Column('marketcap_task_id', sa.Integer(), nullable=True),
        sa.Column('stage_analysis_task_id', sa.Integer(), nullable=True),
        sa.Column('stock_stage_task_id', sa.Integer(), nullable=True),
        sa.Column('rs_calculation_task_id', sa.Integer(), nullable=True),
        sa.Column('volume_dryup_task_id', sa.Integer(), nullable=True),
        sa.Column('step_details', sa.Text(), nullable=True),
        sa.Column('error_details', sa.Text(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['download_task_id'], ['download_tasks.id'], ),
        sa.ForeignKeyConstraint(['marketcap_task_id'], ['marketcap_fetch_tasks.id'], ),
        sa.ForeignKeyConstraint(['rs_calculation_task_id'], ['rs_calculation_tasks.id'], ),
        sa.ForeignKeyConstraint(['stage_analysis_task_id'], ['stage_analysis_tasks.id'], ),
        sa.ForeignKeyConstraint(['stock_stage_task_id'], ['stock_stage_analysis_tasks.id'], ),
        sa.ForeignKeyConstraint(['sync_task_id'], ['sync_tasks.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['volume_dryup_task_id'], ['volume_dryup_tasks.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('master_sync_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_sync_tasks_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_sync_tasks_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_sync_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_sync_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_master_sync_tasks_user_id'))

    op.drop_table('master_sync_tasks')
    # ### end Alembic commands ###
