"""Add sub_sector_id to instruments and missing sector columns

Revision ID: d3cc5a8e5507
Revises: 27ba45b34787
Create Date: 2025-11-03 22:56:50.009120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cc5a8e5507'
down_revision = '27ba45b34787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_sector_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_instruments_sub_sector_id'), ['sub_sector_id'], unique=False)
        batch_op.create_foreign_key('fk_instruments_sub_sector_id', 'sub_sectors', ['sub_sector_id'], ['id'])

    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_sectors_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sectors_is_active'))
        batch_op.drop_column('display_order')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_instruments_sub_sector_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_instruments_sub_sector_id'))
        batch_op.drop_column('sub_sector_id')

    # ### end Alembic commands ###
