"""Add last_traded_price and outstanding_shares to stock_information

Revision ID: e2ce413e3c5d
Revises: 02de6ea09777
Create Date: 2025-11-05 20:28:15.524918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ce413e3c5d'
down_revision = '02de6ea09777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_traded_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('outstanding_shares', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_information', schema=None) as batch_op:
        batch_op.drop_column('outstanding_shares')
        batch_op.drop_column('last_traded_price')

    # ### end Alembic commands ###
