"""Add float_shares to stock_information

Revision ID: fce52a7b285b
Revises: e2ce413e3c5d
Create Date: 2025-11-05 21:31:34.773188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce52a7b285b'
down_revision = 'e2ce413e3c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('float_shares', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_information', schema=None) as batch_op:
        batch_op.drop_column('float_shares')

    # ### end Alembic commands ###
